# Site settings
title: Leah Englund-Brick
email: leah.englund@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Leah Englund-Brick
baseurl: "" # the subpath of your site, e.g. /blog/
url: "leahenglundbrick.net" # the base hostname & protocol for your site
twitter_username: leah.englund
github_username:  leahenglundbrick

# Build settings
markdown: kramdown
